language: generic

sudo: required

dist: trusty

services:
  - docker

before_install:
  - sudo pip install --user codecov

install:
  - docker pull lamtev/java

script:
  - docker run -v $TRAVIS_BUILD_DIR:/radix-converter lamtev/java /bin/bash -c " cd radix-converter && gradle build "
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
